### ISSUE TITLE
tedrl-apid doesn't run

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/tendrl-api#30]
I've tried to run tendrl-apid by command from systemd unit file https://github.com/Tendrl/tendrl-api/blob/master/tendrl-apid.service and it doesn't work:
```
$ /usr/bin/puma -e production --dir /usr/share/tendrl-api/
Puma starting in single mode...
* Version 3.6.0 (ruby 2.0.0-p598), codename: Sleepy Sunday Serenity
* Min threads: 0, max threads: 16
* Environment: production
! Unable to load application: Bundler::GemNotFound: Your bundle is locked to rake (0.9.6), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of rake (0.9.6) has removed it. You'll need to update your bundle to a different version of rake (0.9.6) that hasn't been removed in order to install.
/usr/share/gems/gems/bundler-1.13.6/lib/bundler/definition.rb:179:in `rescue in specs': Your bundle is locked to rake (0.9.6), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of rake (0.9.6) has removed it. You'll need to update your bundle to a different version of rake (0.9.6) that hasn't been removed in order to install. (Bundler::GemNotFound)
	from /usr/share/gems/gems/bundler-1.13.6/lib/bundler/definition.rb:173:in `specs'
	from /usr/share/gems/gems/bundler-1.13.6/lib/bundler/definition.rb:233:in `specs_for'
	from /usr/share/gems/gems/bundler-1.13.6/lib/bundler/runtime.rb:19:in `setup'
	from /usr/share/gems/gems/bundler-1.13.6/lib/bundler.rb:101:in `setup'
	from /usr/share/gems/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
	from /usr/share/tendrl-api/base.rb:9:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/tendrl-api/node.rb:1:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from config.ru:2:in `block in <main>'
	from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /usr/share/gems/gems/puma-3.6.0/lib/puma/configuration.rb:315:in `load_rackup'
	from /usr/share/gems/gems/puma-3.6.0/lib/puma/configuration.rb:243:in `app'
	from /usr/share/gems/gems/puma-3.6.0/lib/puma/runner.rb:127:in `load_and_bind'
	from /usr/share/gems/gems/puma-3.6.0/lib/puma/single.rb:85:in `run'
	from /usr/share/gems/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
	from /usr/share/gems/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
	from /usr/share/gems/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
	from /usr/bin/puma:23:in `load'
	from /usr/bin/puma:23:in `<main>'
```
Also I've tried to put this command for last package tendrl-api-0.0.1-8.el7.centos.noarch because unit file there has some issues described here https://github.com/Tendrl/tendrl-api/issues/27
And I've tried to run tendrl-apid service:
```
systemctl status -l tendrl-apid
● tendrl-apid.service - Tendrl Api Daemon
   Loaded: loaded (/usr/lib/systemd/system/tendrl-apid.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Thu 2016-12-01 10:32:50 UTC; 9min ago
 Main PID: 22242 (code=exited, status=1/FAILURE)

Dec 01 10:32:50 usm5-server.usmqe systemd[1]: Unit tendrl-apid.service entered failed state.
Dec 01 10:32:50 usm5-server.usmqe systemd[1]: tendrl-apid.service failed.
Dec 01 10:32:50 usm5-server.usmqe systemd[1]: tendrl-apid.service holdoff time over, scheduling restart.
Dec 01 10:32:50 usm5-server.usmqe systemd[1]: start request repeated too quickly for tendrl-apid.service
Dec 01 10:32:50 usm5-server.usmqe systemd[1]: Failed to start Tendrl Api Daemon.
Dec 01 10:32:50 usm5-server.usmqe systemd[1]: Unit tendrl-apid.service entered failed state.
Dec 01 10:32:50 usm5-server.usmqe systemd[1]: tendrl-apid.service failed
```

It seems that last package has wrong dependencies.

**Comment by TimothyAsir** [comment]
Make sure you have installed tendrl-api, tendrl-api-httpd, tendrl-api-doc
and configure the etcd details in /etc/tendrl/tendrl.yml
and started httpd service and tendrl-apid service

Can you past here the results of 
1) rpm -qa | grep tendrl
    rpm -qa | grep puma
2) ls -la /usr/share/tendrl-api/
3) Also can you please provide us the first 10 lines from file /usr/share/tendrl-api/lib/tendrl.ru
head +10 /usr/share/tendrl-api/lib/tendrl.rb

**Comment by mkudlej** [comment]
```
rubygem-puma-3.6.0-3.el7.centos.x86_64
tendrl-api-httpd-0.0.1-8.el7.centos.noarch
tendrl-api-0.0.1-8.el7.centos.noarch
tendrl-api-doc-0.0.1-8.el7.centos.noarch
```
```
ls -la /usr/share/tendrl-api/
total 32
drwxr-xr-x.  4 root root 4096 Dec  1 13:06 .
drwxr-xr-x. 78 root root 4096 Dec  1 13:14 ..
-rw-r--r--.  1 root root 1563 Nov 21 21:53 base.rb
-rw-r--r--.  1 root root 2993 Nov 21 21:53 cluster.rb
-rw-r--r--.  1 root root  129 Nov 21 21:53 config.ru
-rw-r--r--.  1 root root  350 Nov 21 21:53 Gemfile
-rw-r--r--.  1 root root 1686 Nov 21 21:53 Gemfile.lock
drwxr-xr-x.  3 root root   35 Dec  1 13:06 lib
-rw-r--r--.  1 root root 1164 Nov 21 21:53 node.rb
drwxr-xr-x.  2 root root    6 Nov 21 21:53 public
```

```
$ head -10 /usr/share/tendrl-api/lib/tendrl.rb
require 'active_support/core_ext/hash/deep_merge'
require './lib/tendrl/version'
require './lib/tendrl/flow'
require './lib/tendrl/object'
require './lib/tendrl/atom'
require './lib/tendrl/attribute'

#Errors
require './lib/tendrl/errors/tendrl_error'
require './lib/tendrl/errors/invalid_object_error'
```

**Comment by TimothyAsir** [comment]
looks like you are using wrong repo.
Please uninstall the tendrl-api* packages and install the correct repo using
https://copr.fedorainfracloud.org/coprs/tendrl/tendrl/repo/epel-7/tendrl-tendrl-epel-7.repo
and install the tendrl-api* packages.

you can install the repo using
wget https://copr.fedorainfracloud.org/coprs/tendrl/tendrl/repo/epel-7/tendrl-tendrl-epel-7.repo -P /etc/yum.repos.d/

then "yum clean all"
then install tendrl-api, tendrl-api-httpd, tendrl-api-doc rpms

and let me know the status please.

**Comment by TimothyAsir** [comment]
Also check /etc/yum.repos.d directory and remove any repo file pointing to old repo [timothyasir-tendrl]
https://copr.fedorainfracloud.org/coprs/timothyasir/tendrl/repo/epel-7/timothyasir-tendrl-epel-7.repo

**Comment by fbalak** [comment]
After installing tendrl-api from https://copr-be.cloud.fedoraproject.org/results/tendrl/tendrl/epel-7-x86_64/ service tendrl-apid runs.

**Comment by TimothyAsir** [comment]
Great!, We can close this issue as resolved

**Comment by TimothyAsir** [comment]
Since this issue is resolved, i a closing this
